#!/usr/bin/env zsh

# Change directory and open in Visual Studio Code
#
# Dependencies:
# - fzf
#
# Usage:
#
# ```bash
# cdc
# ```
#

function cdc {
  cd $(find ~/git -mindepth 0 -maxdepth 3 -type d -name .git -prune -exec dirname {} \; | fzf) && code .
}
