#!/usr/bin/env zsh

# [cd] to [p]rojects
# This function is similar to cdc, but it doesn't open the project in VS Code.
#
# Dependencies:
# - fzf
#
# Usage:
#
# ```bash
# cdp
# ```
#

function cdp {
	local projects_path="$HOME/git"
	local selected_path
	selected_path=$(
		find "$projects_path" -mindepth 0 -maxdepth 3 -type d -name .git -prune -exec dirname {} \; |
			awk -v home="$HOME" '{
      display = $0
      sub("^" home, "~", display)
      print display ":" $0
    }' |
			fzf \
				--delimiter=':' \
				--with-nth='{1}' \
				--accept-nth=2
	)

	if [[ -n "$selected_path" ]]; then
		cd "$selected_path"
	fi
}
