#!/usr/bin/env zsh

# [g]it [b]ranch [f]ind – Show all git branches and checkout the selected one
# 
# Dependencies:
# - fzf
#
# Usage:
#
# ```bash
# gbf
# ```
#

function gbf {
  git_log_format="git log --graph --pretty=format:'%C(yellow)%ad%Creset %C(white)%s%Creset %C(bold yellow)%d%Creset %C(bold blue)<%an>%Cr    eset' --color=always --date=short"
  git for-each-ref \
    --color=always  \
    --sort=-committerdate refs/heads/ \
    --format='%(color:yellow)%(committerdate:relative)%(color:reset) %09 %(color:reset)%(if)%(HEAD)%(then)%(color:green)%(end) %(HEAD) %(refname:short)' \
  | fzf \
    --ansi \
    --header "Git branches | ctrl-f preview down, ctrl-b preview up" \
    --bind "ctrl-f:preview-page-down,ctrl-b:preview-page-up" \
    --bind "ctrl-o:execute:$eval($git_log_format)" \
    --preview="$git_log_format -50 \$(echo {} | awk '{print \$NF}')" \
  | awk '{print $NF}' \
  | xargs git checkout
}
