#!/usr/bin/env zsh

# Git log with a nice preview of the diff from the commit
# 
# [g]it [l]o[g] 
# 
# From https://github.com/exosyphon/dotfiles/blob/main/scripts/fshow.sh
#
# Dependencies:
# - fzf
#
# Usage:
#
# ```bash
# glg
# ```
#

function glg {
  git log --graph --color=always \
      --format="%C(auto)%h%d %s %C(blue)%C(bold)%cr" "$@" |
  fzf --ansi --no-sort --reverse --tiebreak=index --bind=ctrl-s:toggle-sort --preview \
         'f() { set -- $(echo -- "$@" | grep -o "[a-f0-9]\{7\}"); [ $# -eq 0 ] || git show --color=always $1 ; }; f {}' \
      --header "enter to view, ctrl-o to checkout" \
      --bind "ctrl-f:preview-page-down,ctrl-b:preview-page-up" \
      --bind "ctrl-o:become:(echo {} | grep -o '[a-f0-9]\{7\}' | head -1 | xargs git checkout)" \
      --bind "ctrl-m:execute:
                (grep -o '[a-f0-9]\{7\}' | head -1 |
                xargs -I % sh -c 'git show --color=always % | less -R') << 'FZF-EOF'
                {}
FZF-EOF" --preview-window=right:40%
}
