#!/usr/bin/env zsh

# Fuzzy find npm scripts
#
# This will list all the npm scripts in the current project and allow you to fuzzy find and run them.
#
# Dependencies:
# - jq
# - fzf
#
# Usage:
#
# ```bash
# npmr
# ```

function npmr {
	local selected_script=$(
		jq -r '.scripts | to_entries[] | "\(.key)\t\(.value)"' package.json |
			fzf --with-nth=1 \
				--accept-nth=1 \
				--preview "echo {} | cut -f2"
	)
	if [[ -z "$selected_script" ]]; then
		return 0
	fi
	local current_dir_name=$(basename "$PWD")
	echo -ne "\e]2;$current_dir_name: npm run $selected_script \a"
	echo "$selected_script" | xargs -r npm run
}
